apiVersion: apps/v1
kind: Deployment
metadata:
  name: ncloud-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ncloud-cli
  template:
    metadata:
      labels:
        app: ncloud-cli
    spec:
      containers:
        - name: ncloud-cli
          image: aidt-container-registry.ncr.gov-ntruss.com/ncloud-cli
          imagePullPolicy: IfNotPresent
          command: [ "tail", "-f", "/dev/null" ]  # 계속 살아 있도록 설정
          env:
            - name: NCLOUD_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ncloud-secret
                  key: accessKey
            - name: NCLOUD_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ncloud-secret
                  key: secretKey
