apiVersion: apps/v1
kind: Deployment
metadata:
  name: ncloud-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ncloud-cli
  template:
    metadata:
      labels:
        app: ncloud-cli
    spec:
      imagePullSecrets:
      - name: ncloud-reg-cred
      containers:
        - name: ncloud-cli
          image: navercloud-cli:latest
          imagePullPolicy: IfNotPresent
          command: [ "tail", "-f", "/dev/null" ]  # 계속 살아 있도록 설정
          env:
            - name: NCLOUD_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: ncloud-secret
                  key: ncloud_access_key_id
            - name: NCLOUD_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ncloud-secret
                  key: ncloud_secret_access_key
            - name: NCLOUD_API_URL
              valueFrom:
                secretKeyRef:
                  name: ncloud-secret
                  key: ncloud_api_url
